import { Enum } from 'cc';

/**
 * Все стандартные easing-функции Cocos Creator для твинов (отсортированы по алфавиту)
 * В инспекторе Enum корректно отображается только с числовыми значениями.
 */
export const TweenType = Enum({
    BackIn: 0,
    BackInOut: 1,
    BackOut: 2,
    BounceIn: 3,
    BounceInOut: 4,
    BounceOut: 5,
    CircIn: 6,
    CircInOut: 7,
    CircOut: 8,
    CubicIn: 9,
    CubicInOut: 10,
    CubicOut: 11,
    ElasticIn: 12,
    ElasticInOut: 13,
    ElasticOut: 14,
    ExpoIn: 15,
    ExpoInOut: 16,
    ExpoOut: 17,
    Fade: 18,
    Linear: 19,
    QuadIn: 20,
    QuadInOut: 21,
    QuadOut: 22,
    QuartIn: 23,
    QuartInOut: 24,
    QuartOut: 25,
    QuintIn: 26,
    QuintInOut: 27,
    QuintOut: 28,
    SineIn: 29,
    SineInOut: 30,
    SineOut: 31,
    Smooth: 32,
});

export const TweenTypeValues: Record<number, string> = {
    [TweenType.BackIn]: 'backIn',
    [TweenType.BackInOut]: 'backInOut',
    [TweenType.BackOut]: 'backOut',
    [TweenType.BounceIn]: 'bounceIn',
    [TweenType.BounceInOut]: 'bounceInOut',
    [TweenType.BounceOut]: 'bounceOut',
    [TweenType.CircIn]: 'circIn',
    [TweenType.CircInOut]: 'circInOut',
    [TweenType.CircOut]: 'circOut',
    [TweenType.CubicIn]: 'cubicIn',
    [TweenType.CubicInOut]: 'cubicInOut',
    [TweenType.CubicOut]: 'cubicOut',
    [TweenType.ElasticIn]: 'elasticIn',
    [TweenType.ElasticInOut]: 'elasticInOut',
    [TweenType.ElasticOut]: 'elasticOut',
    [TweenType.ExpoIn]: 'expoIn',
    [TweenType.ExpoInOut]: 'expoInOut',
    [TweenType.ExpoOut]: 'expoOut',
    [TweenType.Fade]: 'fade',
    [TweenType.Linear]: 'linear',
    [TweenType.QuadIn]: 'quadIn',
    [TweenType.QuadInOut]: 'quadInOut',
    [TweenType.QuadOut]: 'quadOut',
    [TweenType.QuartIn]: 'quartIn',
    [TweenType.QuartInOut]: 'quartInOut',
    [TweenType.QuartOut]: 'quartOut',
    [TweenType.QuintIn]: 'quintIn',
    [TweenType.QuintInOut]: 'quintInOut',
    [TweenType.QuintOut]: 'quintOut',
    [TweenType.SineIn]: 'sineIn',
    [TweenType.SineInOut]: 'sineInOut',
    [TweenType.SineOut]: 'sineOut',
    [TweenType.Smooth]: 'smooth',
};